#!/bin/bash

# AIME MLC - Machine Learning Container Management 
# 
# Copyright (c) AIME GmbH and affiliates. Find more info at https://www.aime.info/mlc 
# 
# This software may be used and distributed according to the terms of the MIT LICENSE 

CONFIRMED=false

ARGS=()

for i in "$@"
do
case $i in
    -Y|--yes)
    CONFIRMED=true
    ;;
    -*)
    echo "Unknown option: $i"
    exit -1
    ;;
    *)
    ARGS+=($i)
          # unknown option
    ;;
esac
done

MLC_PATH=$(dirname $0)
cd $MLC_PATH

if [ ! -d "$MLC_PATH/.git" ]
then
  echo "Failed: ML container system not installed as updatable git repo"
  exit -1
fi

SUDO="sudo"
if [ -w "$MLC_PATH/.git" ] 
then
  SUDO=""
fi

BRANCH=$(basename $(git symbolic-ref HEAD))

if [[ $CONFIRMED == false ]]
then
  echo -e "This will update the ML container system to the latest version."
  echo -e ""

  if [[ ! $SUDO == "" ]]
  then
    read -p "Check for available updates? (Y/N) " -n 1 -r
    echo 
    if [[ $REPLY =~ ^[Yy]$ ]]
    then
      echo ""
    else
      exit 0
    fi
  fi

  OUTPUT=$($SUDO git remote update)
  UPDATE_LOG=$($SUDO git log HEAD..origin/$BRANCH --pretty=format:" - %s")
  if [[ $UPDATE_LOG == "" ]]
  then
    echo -e "ML container system is up to date.\n"
    exit -1
  fi

  echo -e "Update(s) available.\n\nChange Log:\n$UPDATE_LOG\n"

  read -p "Update ML container system? (Y/N) " -n 1 -r
  echo 
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    CONFIRMED=true
  else
    exit 0
  fi
fi

{
  echo -e "\nUpdating ML container system ... \n"
  $SUDO git pull origin $BRANCH
  echo ""
  echo -e "AIME MLC v2 is now available. To upgrade, use:\nmlc-upgrade-sys\n"
  exit 1
} 

