#!/bin/bash

echo -e "\nRunning ml-containers are:\n"


OUTPUT=$(docker container stats --format "table [{{index (split .Name \"._.\") 0}}]\t{{.CPUPerc}}\t{{.MemUsage}}" --no-stream
echo -e "")

echo "${OUTPUT/\[78\]   /CONTAINER}"
echo ""
