#!/bin/bash

# AIME MLC - Machine Learning Container Management 
# 
# Copyright (c) AIME GmbH and affiliates. Find more info at https://www.aime.info/mlc 
# 
# This software may be used and distributed according to the terms of the MIT LICENSE 

echo -e "\nRunning ml-containers are:\n"


OUTPUT=$(docker container stats --format "table [{{.Name}}]\t{{.CPUPerc}}\t{{.MemUsage}}" --no-stream
echo -e "")

echo "${OUTPUT/\[NAME\]   /CONTAINER}"
echo ""
