#!/bin/bash

CONFIRMED=false

ARGS=()

for i in "$@"
do
case $i in
    -Y|--yes)
    CONFIRMED=true
    ;;
    -*)
    echo "Unknown option: $i"
    exit -1
    ;;
    *)
    ARGS+=($i)
          # unknown option
    ;;
esac
done

CONTAINER_NAME=${ARGS[0]}

if [[ $CONTAINER_NAME == "" ]]
then
  echo -e "Stop an ml-container"
  echo -e "\nUsage: mlc-stop container_name [-Y]\n"
  exit -1
fi

function check_container_running {
  docker container ps --filter=name=^/$1$ --filter=label=aime.mlc --format "{{.Names}}"
}


CONTAINER_RUNNING=$(check_container_running $CONTAINER_NAME)

if [[ $CONTAINER_NAME != $CONTAINER_RUNNING ]]
then
  echo "["$CONTAINER_NAME"] container not running."
  exit -2
fi

if [[ $CONFIRMED != true ]]
then
	echo -e "This will stop the container ["$CONTAINER_NAME"]."
	echo -e "WARNING: All running processes in the container will be terminated."
	echo -e ""

	read -p "Stop container? (Y/N) " -n 1 -r
	echo 
	if [[ $REPLY =~ ^[Yy]$ ]]
	then
	  CONFIRMED=true
	else
	  exit 0
	fi
fi

if [[ $CONFIRMED == true ]]
then
  echo -e "\n["$CONTAINER_NAME"] Stopping container ..."	
  RESULT=$(docker container stop $CONTAINER_NAME)
  echo -e "["$CONTAINER_NAME"] container stopped.\n"	
fi