#!/bin/bash

LIST_ALL=false

ARGS=()

for i in "$@"
do
case $i in
    -a|--all)
    LIST_ALL=true
	;;
    -h|--help)
    echo -e "List available ml-containers"
    echo -e "\nUsage: mlc-list [-a|--all]\n"
    exit -1
    ;;
    -*)
    echo "Unknown option: $i"
    exit -1
    ;;
    *)
    ARGS+=($i)
    ;;
esac
done


echo -e "\nAvailable ml-containers are:\n"

if [ "$LIST_ALL" = true ] ; then
    FILTER=label=aime.mlc
    OUTPUT=$(docker container ls -a --filter=$FILTER --format "table [{{index (split .Names \"._.\") 0}}]\t{{.Label \"aime.mlc.USER\"}}\t{{.Status}}")
else
    FILTER=label=aime.mlc=$USER
    OUTPUT=$(docker container ls -a --filter=$FILTER --format "table [{{index (split .Names \"._.\") 0}}]\t{{.Label \"aime.mlc.FRAMEWORK\"}}\t{{.Status}}")    
fi

echo "${OUTPUT/\[78\]     /CONTAINER}"

echo -e ""
