#!/bin/bash

# AIME MLC - Machine Learning Container Management 
# 
# Copyright (c) AIME GmbH and affiliates. Find more info at https://www.aime.info/mlc 
# 
# This software may be used and distributed according to the terms of the MIT LICENSE 


# Get the absolute path of the mlc-upgrade-sys file
UPGRADE_PATH="$(realpath "$0")"

# Get the directory where the mlc-upgrade-sys file is located
UPGRADE_DIR="$(dirname "$UPGRADE_PATH")"

if [ -f "$UPGRADE_DIR/mlc.py" ]
then
    echo ""
    echo "AIME MLC system has already been upgraded."
    echo ""
    echo -e "Use mlc --help in the command line or visit https://www.aime.info/mlc to explore the new features."
    echo ""
    exit 0
fi

#Check if sudo rights are needed:
SUDO="sudo"
if [ -w "$UPGRADE_DIR" ] 
then
  SUDO=""
fi

echo ""
echo -e "Starting the upgrade from AIME MLC v1 to AIME MLC v2.\nAll files and folders in $UPGRADE_DIR will be deleted.\nIf you have manually copied or moved any important data into this folder, please back it up before proceeding."

while true; do
    read -p "Do you want to continue (Y/N)?: " -n 1 -r
    echo ""
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        break  
    elif [[ $REPLY =~ ^[Nn]$ ]]; then
        exit 0  
    else
        echo "Invalid input. Please enter Y or N."
        echo ""
    fi
done

echo ""
echo -e "Deleting the previous version files of AIME MLC v1 from $UPGRADE_DIR..."
echo ""

# Remove all files and folders except for the mlc-upgrade-sys script itself
$SUDO find "$UPGRADE_DIR" -mindepth 1 ! -name "$(basename "$UPGRADE_PATH")" -exec rm -rf {} +

echo -e "Installing the latest version files of AIME MLC v2..."
echo ""

# Git repo of the AIME MLC v2:
REPO_MLCV2="https://github.com/aime-team/aime-mlc"

# Clone the repository into the script's directory
$SUDO git clone $REPO_MLCV2 "$UPGRADE_DIR/aime-mlc"

$SUDO mv $UPGRADE_DIR/aime-mlc/{*,.*} $UPGRADE_DIR/ 2>/dev/null

echo ""
echo -e "Deleting unnecesary files and directories..."
echo ""

# Delete the empty directory ./aime-mlc
$SUDO rmdir $UPGRADE_DIR/aime-mlc/

echo -e "Upgrade from AIME MLC v1 to v2 completed successfully."
echo ""
echo -e "Use mlc --help in the command line or visit https://www.aime.info/mlc to explore the new features."
echo ""
