#!/bin/bash

# AIME MLC - Machine Learning Container Management 
# 
# Copyright (c) AIME GmbH and affiliates. Find more info at https://www.aime.info/mlc 
# 
# This software may be used and distributed according to the terms of the MIT LICENSE 

CONFIRMED=false

ARGS=()

for i in "$@"
do
case $i in
    -Y|--yes)
    CONFIRMED=true
    ;;
    -*)
    echo "Unknown option: $i"
    exit -1
    ;;
    *)
    ARGS+=($i)
          # unknown option
    ;;
esac
done

CONTAINER_NAME=${ARGS[0]}

if [[ $CONTAINER_NAME == "" ]]
then
  echo -e "Stop an ml-container"
  echo -e "\nUsage: mlc-stop container_name [-Y]\n"
  exit -1
fi

function check_container_exists {
  docker container ps -a --filter=name=^/$1$ --filter=label=aime.mlc --format "{{.Names}}"
}

function check_container_running {
  docker container ps --filter=name=^/$1$ --filter=label=aime.mlc --format "{{.Names}}"
}


USER_ID=$(id -u)
GROUP_ID=$(id -g)
CONTAINER_TAG=$CONTAINER_NAME._.$USER_ID

if [[ $CONTAINER_TAG != $(check_container_exists $CONTAINER_TAG) ]]
then  
  CONTAINER_TAG=$CONTAINER_NAME
  if [[ $CONTAINER_TAG != $(check_container_exists $CONTAINER_TAG) ]]
  then
    echo "["$CONTAINER_NAME"] does not exist."
    exit -3
  fi
fi

CONTAINER_RUNNING=$(check_container_running $CONTAINER_TAG)

if [[ $CONTAINER_TAG != $CONTAINER_RUNNING ]]
then
  echo "["$CONTAINER_NAME"] container not running."
  exit -2
fi

if [[ $CONFIRMED != true ]]
then
	echo -e "This will stop the container ["$CONTAINER_NAME"]."
	echo -e "WARNING: All running processes in the container will be terminated."
	echo -e ""

	read -p "Stop container? (Y/N) " -n 1 -r
	echo 
	if [[ $REPLY =~ ^[Yy]$ ]]
	then
	  CONFIRMED=true
	else
	  exit 0
	fi
fi

if [[ $CONFIRMED == true ]]
then
  echo -e "\n["$CONTAINER_NAME"] Stopping container ..."	
  RESULT=$(docker container stop $CONTAINER_TAG)
  echo -e "["$CONTAINER_NAME"] container stopped.\n"	
fi