#!/bin/bash

CONFIRMED=false

ARGS=()

for i in "$@"
do
case $i in
    -Y|--yes)
    CONFIRMED=true
    ;;
    -*)
    echo "Unknown option: $i"
    exit -1
    ;;
    *)
    ARGS+=($i)
          # unknown option
    ;;
esac
done

MLC_PATH=$(dirname $0)

if [[ $CONFIRMED == false ]]
then
  echo -e "This will update the ML container system to the latest version."
  echo -e ""

  read -p "Update ML container system? (Y/N) " -n 1 -r
  echo 
  if [[ $REPLY =~ ^[Yy]$ ]]
  then
    CONFIRMED=true
  else
    exit 0
  fi
fi

{
  echo -e "\nUpdating ML container system ... \n"
  cd $MLC_PATH
  BRANCH=$(basename $(git symbolic-ref HEAD))
  sudo git pull origin $BRANCH
  exit
} 

